import Anthropic from "@anthropic-ai/sdk";
import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { alertCronFailure } from "@/lib/cron-alert";

/**
 * Daily macro-economic briefing — generated by a Vercel cron.
 *
 * Pipeline (cheapest path that stays "premium & complete"):
 *   1. Pull the next 7 days of high/medium scheduled events from the shared
 *      `economic_events` cache (no extra cost — already in our DB).
 *   2. Generate ONE briefing in French with Sonnet + the server-side web_search
 *      tool, so the model has FRESH context (geopolitics, central banks, shocks)
 *      it cannot know from its training cut-off alone. No third-party news API.
 *   3. Translate that briefing to en/de/es with Haiku (far cheaper than four
 *      web-search generations).
 *   4. Upsert all four rows into `macro_analyses`, keyed (date, lang). Served to
 *      every premium member — generated once, read by all.
 *
 * This is an informational CONTEXT briefing, never a buy/sell recommendation —
 * the prompt enforces that, consistent with the rest of the product.
 *
 * Defensive: missing API key / feed / parse failure degrade gracefully and the
 * route reports what it did rather than 500-ing the whole cron.
 *
 * To raise quality at higher cost, switch BRIEF_MODEL to "claude-opus-4-8".
 */

export const dynamic = "force-dynamic";
// Web search + four model calls can take a while; give the cron room.
export const maxDuration = 300;

type Lang = "fr" | "en" | "de" | "es";
const TARGET_LANGS: Lang[] = ["en", "de", "es"]; // FR is the source language

const BRIEF_MODEL = "claude-sonnet-4-6";
const TRANSLATE_MODEL = "claude-haiku-4-5";

// The brief is a rich JSON (overview + 3-5 themes + 3-5 watchlist + 3 outlook
// horizons + takeaway). At 4000 tokens it was hitting `stop_reason=max_tokens`
// and truncating the JSON mid-string → parse failure → 502 → no briefing saved
// that day. Give it ample headroom; cost scales with tokens actually generated,
// not the cap, so a normal day stays cheap.
const BRIEF_MAX_TOKENS = 8000;

// Hard wall-clock budget for the brief phase. Vercel kills the function at 300s
// (→504, nothing persisted); we reserve the rest for translations + DB writes.
const BRIEF_BUDGET_MS = 220_000;

const LANG_NAME: Record<Lang, string> = {
  fr: "français",
  en: "English",
  de: "Deutsch",
  es: "español",
};

interface Section {
  title: string;
  body: string;
}

interface Outlook {
  today: string;
  days: string;
  months: string;
}

interface Analysis {
  headline: string;
  overview: string;
  themes: Section[];
  watchlist: Section[];
  outlook: Outlook;
  takeaway: string;
}

// JSON schema for the translation step. Structured outputs guarantee valid,
// parseable JSON (no unescaped quotes / markdown), which the free-form prompt
// could not — that was causing some translations to fail and fall back to FR.
// Only used for translations: the brief uses web_search (→ citations), which is
// incompatible with structured outputs.
const sectionSchema = {
  type: "object",
  additionalProperties: false,
  properties: { title: { type: "string" }, body: { type: "string" } },
  required: ["title", "body"],
} as const;

const ANALYSIS_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    headline: { type: "string" },
    overview: { type: "string" },
    themes: { type: "array", items: sectionSchema },
    watchlist: { type: "array", items: sectionSchema },
    outlook: {
      type: "object",
      additionalProperties: false,
      properties: {
        today: { type: "string" },
        days: { type: "string" },
        months: { type: "string" },
      },
      required: ["today", "days", "months"],
    },
    takeaway: { type: "string" },
  },
  required: ["headline", "overview", "themes", "watchlist", "outlook", "takeaway"],
} as const;

function serviceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

/** Concatenate the model's final text blocks (ignoring web_search tool blocks). */
function textOf(msg: Anthropic.Message): string {
  return msg.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("")
    .trim();
}

/** Extract and validate the JSON object from a model response. */
function parseAnalysis(raw: string): Analysis | null {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) return null;
  let parsed: Partial<Analysis>;
  try {
    parsed = JSON.parse(match[0]) as Partial<Analysis>;
  } catch {
    return null;
  }
  if (!parsed.headline || !parsed.overview) return null;
  const o = parsed.outlook ?? ({} as Partial<Outlook>);
  return {
    headline: String(parsed.headline),
    overview: String(parsed.overview),
    themes: Array.isArray(parsed.themes)
      ? parsed.themes.filter((s): s is Section => !!s?.title && !!s?.body)
      : [],
    watchlist: Array.isArray(parsed.watchlist)
      ? parsed.watchlist.filter((s): s is Section => !!s?.title && !!s?.body)
      : [],
    outlook: {
      today: o.today ? String(o.today) : "",
      days: o.days ? String(o.days) : "",
      months: o.months ? String(o.months) : "",
    },
    takeaway: parsed.takeaway ? String(parsed.takeaway) : "",
  };
}

/**
 * Run a request that uses the server-side web_search tool to completion.
 *
 * We use the classic `web_search_20250305` (not the dynamic-filtering
 * `web_search_20260209`): the newer tool runs server-side CODE EXECUTION per
 * search, which is far slower and less predictable — it blew past Vercel's hard
 * 300s function cap (504) and even tripped the SDK request timeout locally. The
 * classic tool just returns results, so it's fast and steady.
 *
 * The server loops a few searches then may return `pause_turn`; we resume a
 * couple of times. Each call is capped at 120s so a hung search fails fast
 * (cron retries next day) instead of burning the whole budget.
 */
async function createWithWebSearch(
  client: Anthropic,
  prompt: string,
  deadline: number,
): Promise<Anthropic.Message> {
  const messages: Anthropic.MessageParam[] = [{ role: "user", content: prompt }];
  const tools = [
    { type: "web_search_20250305" as const, name: "web_search" as const, max_uses: 5 },
  ];
  // Each call may only use the time left in the budget, capped at 150s.
  const callTimeout = () =>
    Math.max(20_000, Math.min(150_000, deadline - Date.now()));
  let msg = await client.messages.create(
    { model: BRIEF_MODEL, max_tokens: BRIEF_MAX_TOKENS, tools, messages },
    { timeout: callTimeout() },
  );
  let guard = 0;
  // Resume pause_turns only while a safe budget remains. On a slow morning these
  // can chain (each search adds another model call), and the classic 1+3 loop
  // could exceed Vercel's 300s cap → 504 with nothing saved.
  while (msg.stop_reason === "pause_turn" && guard < 3 && deadline - Date.now() > 40_000) {
    guard++;
    messages.push({ role: "assistant", content: msg.content });
    msg = await client.messages.create(
      { model: BRIEF_MODEL, max_tokens: BRIEF_MAX_TOKENS, tools, messages },
      { timeout: callTimeout() },
    );
  }
  return msg;
}

async function handle(req: Request) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const apiKey = process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    await alertCronFailure("macro-analysis/generate", "No Anthropic API key configured.");
    return NextResponse.json({ error: "No API key" }, { status: 500 });
  }

  let supabase;
  try {
    supabase = serviceClient();
  } catch {
    return NextResponse.json({ error: "No Supabase config" }, { status: 500 });
  }

  const url = new URL(req.url);
  const dryRun = url.searchParams.get("dryRun") === "1";
  const today = new Date();
  const analysisDate = today.toISOString().split("T")[0];

  // ── 1. Scheduled calendar context (next 7 days, high/medium impact) ───────
  let calendarContext = "";
  try {
    const in7 = new Date(today);
    in7.setDate(in7.getDate() + 7);
    const { data: events } = await supabase
      .from("economic_events")
      .select("event_time, currency, title, impact, forecast, previous")
      .gte("event_time", today.toISOString())
      .lte("event_time", in7.toISOString())
      .in("impact", ["high", "medium"])
      .order("event_time", { ascending: true })
      .limit(40);
    if (events && events.length > 0) {
      calendarContext = events
        .map((e) => {
          const d = new Date(e.event_time as string).toISOString().split("T")[0];
          return `- ${d} ${e.currency} ${e.title} (${e.impact})`;
        })
        .join("\n");
    }
  } catch {
    // economic_events not migrated / unavailable → brief still works via web search.
  }

  const client = new Anthropic({ apiKey });

  // ── 2. Generate the French briefing with fresh web context ────────────────
  const briefPrompt = `Tu es un analyste macro-économique senior. Nous sommes le ${analysisDate}.

Rédige l'analyse macro-économique du jour pour des traders. Utilise l'outil de recherche web pour t'appuyer sur l'actualité RÉELLE et RÉCENTE : situation de l'économie mondiale, décisions et discours des banques centrales (Fed, BCE, etc.), inflation et croissance, tensions géopolitiques et conflits, chocs sur l'énergie ou les matières premières, et tout événement marquant susceptible d'influencer les marchés. Cherche des informations datées de ces derniers jours.

${calendarContext ? `Annonces économiques programmées dans les 7 prochains jours (à intégrer dans ce qu'il faut surveiller) :\n${calendarContext}\n` : ""}
RÈGLES IMPÉRATIVES :
- C'est une analyse de CONTEXTE informative, JAMAIS un conseil. N'écris jamais « achète », « vends », « long », « short » ni aucune recommandation de position.
- Appuie-toi sur des faits réels trouvés par la recherche web. N'invente aucun chiffre.
- Reste factuel, nuancé et pédagogue. Pas de sensationnalisme.

Réponds STRICTEMENT en JSON, sans markdown ni texte autour, avec cette forme exacte :
{
  "headline": "titre d'une ligne qui résume l'ambiance macro du jour",
  "overview": "un paragraphe (4-6 phrases) sur l'état général de l'économie mondiale et le climat de marché",
  "themes": [
    { "title": "thème clé", "body": "2-3 phrases expliquant ce thème et son impact potentiel sur les marchés" }
  ],
  "watchlist": [
    { "title": "événement ou risque à surveiller", "body": "1-2 phrases : pourquoi c'est important et ce que ça pourrait déclencher" }
  ],
  "outlook": {
    "today": "impacts CONCRETS attendus pour la séance du jour, classe d'actifs par classe d'actifs (indices actions, EUR/USD et dollar, taux/obligations, or, pétrole/énergie) : décris les dynamiques probables et leur logique",
    "days": "impacts attendus sur les prochains jours / cette semaine, en lien avec les annonces et événements à venir",
    "months": "tendances de fond attendues sur les prochaines semaines / mois"
  },
  "takeaway": "une phrase de synthèse sur le contexte (pas une recommandation)"
}
Donne 3 à 5 thèmes et 3 à 5 éléments à surveiller. Pour "outlook", sois CONCRET et chiffré quand c'est pertinent, en nommant les classes d'actifs et les dynamiques attendues (hausse/baisse de volatilité, pression sur tel actif, etc.) — mais reste une analyse de CONTEXTE : décris ce à quoi s'attendre, ne dis JAMAIS d'acheter, vendre, ou prendre une position. Reste concis.`;

  let frBrief: Analysis | null = null;
  let briefErr: unknown = null;
  try {
    const msg = await createWithWebSearch(client, briefPrompt, Date.now() + BRIEF_BUDGET_MS);
    frBrief = parseAnalysis(textOf(msg));
  } catch (err) {
    briefErr = err;
    console.error("[Macro] FR generation failed:", err);
  }

  if (!frBrief) {
    await alertCronFailure(
      "macro-analysis/generate",
      `FR generation failed for ${analysisDate}. ${briefErr instanceof Error ? briefErr.message : "Model returned an unparseable briefing (possible timeout or truncation)."}`,
    );
    return NextResponse.json({ error: "FR generation failed" }, { status: 502 });
  }

  if (dryRun) {
    return NextResponse.json({ dryRun: true, date: analysisDate, fr: frBrief });
  }

  // ── 3. Persist FR, then translate to the other languages (in parallel) ────
  const fr = frBrief; // non-null narrowing for the closures below
  const translate = async (lang: Lang): Promise<{ lang: Lang; analysis: Analysis; model: string }> => {
    try {
      const tMsg = await client.messages.create(
        {
          model: TRANSLATE_MODEL,
          max_tokens: 8192,
          output_config: { format: { type: "json_schema", schema: ANALYSIS_SCHEMA } },
          messages: [
            {
              role: "user",
              content: `Traduis fidèlement en ${LANG_NAME[lang]} TOUTES les valeurs textuelles de ce JSON d'analyse macro-économique. Garde EXACTEMENT la même structure et les mêmes clés. Ne traduis pas les clés. Ne change pas les chiffres ni les noms propres :

${JSON.stringify(fr)}`,
            },
          ],
        },
        { timeout: 150_000 },
      );
      const translated = parseAnalysis(textOf(tMsg));
      if (translated) return { lang, analysis: translated, model: TRANSLATE_MODEL };
      console.error(`[Macro] ${lang} translation unparseable; falling back to FR`);
    } catch (err) {
      console.error(`[Macro] ${lang} translation failed; falling back to FR:`, err);
    }
    return { lang, analysis: fr, model: BRIEF_MODEL };
  };

  const rows: { lang: Lang; analysis: Analysis; model: string }[] = [
    { lang: "fr", analysis: fr, model: BRIEF_MODEL },
    ...(await Promise.all(TARGET_LANGS.map(translate))),
  ];

  const { error } = await supabase.from("macro_analyses").upsert(
    rows.map((r) => ({
      analysis_date: analysisDate,
      lang: r.lang,
      headline: r.analysis.headline,
      overview: r.analysis.overview,
      themes: r.analysis.themes,
      watchlist: r.analysis.watchlist,
      outlook: r.analysis.outlook,
      takeaway: r.analysis.takeaway,
      model: r.model,
    })),
    { onConflict: "analysis_date,lang" },
  );

  if (error) {
    console.error("[Macro] upsert failed:", error);
    await alertCronFailure("macro-analysis/generate", `Upsert failed for ${analysisDate}: ${error.message}`);
    return NextResponse.json({ error: "Upsert failed", detail: error.message }, { status: 500 });
  }

  // Housekeeping: keep ~1 year of briefings for the history view.
  const cutoff = new Date(today);
  cutoff.setDate(cutoff.getDate() - 365);
  await supabase
    .from("macro_analyses")
    .delete()
    .lt("analysis_date", cutoff.toISOString().split("T")[0]);

  return NextResponse.json({ date: analysisDate, langs: rows.map((r) => r.lang) });
}

// Vercel crons invoke via GET; POST kept for manual testing.
export async function GET(req: Request) {
  return handle(req);
}
export async function POST(req: Request) {
  return handle(req);
}
