-- Add checklist_setup_mapping column to strategies
-- Stores the AI-generated mapping between checklist item values (snake_case)
-- and the setup values they semantically match.
-- Format: { "checklist_item_value": ["setup_value_1", "setup_value_2"], ... }
ALTER TABLE strategies
ADD COLUMN IF NOT EXISTS checklist_setup_mapping JSONB DEFAULT '{}'::jsonb;

COMMENT ON COLUMN strategies.checklist_setup_mapping IS 'AI-generated mapping between checklist items (snake_case value) and the setups they semantically match (array of setup values). Generated by /api/parse-strategy when the user submits their strategy. Empty object {} for legacy strategies that predate this feature.';
