import jsPDF from "jspdf";
import { Pdf, C, money, signedMoney, groupNum, type RGB } from "@/lib/pdf/kit";
import { ensureBrandFont } from "@/lib/pdf/fonts";

/**
 * Rapport PDF de l'analyse IA de discipline — design brandé (kit lib/pdf/kit).
 *
 * Le rapport reprend toute l'analyse nouvelle génération : verdict, KPI,
 * coût de l'indiscipline avec courbe contrefactuelle (réel vs discipline
 * respectée), violations chiffrées, patterns avec preuves, edge, revue des
 * trades notés A-D et plan d'action.
 *
 * La page appelante fournit des chaînes DÉJÀ traduites (titres de violations,
 * segments d'edge…) : ce module ne connaît que les libellés de structure.
 */

export interface AnalysisPdfData {
  lang: "fr" | "en" | "de" | "es";
  periodLabel: string;
  score: number;
  totalTrades: number;
  headline?: string | null;
  summary?: string | null;
  stats?: {
    netPnl: number;
    winRate: number;
    profitFactor: number | null;
    violationCost: number;
    violationTradeCount: number;
  } | null;
  counterfactual?: {
    points: { real: number; clean: number }[];
    realFinal: number;
    cleanFinal: number;
    gain: number;
  } | null;
  violations: { title: string; explanation: string; cost?: number | null }[];
  patterns: { title: string; description: string; evidence?: string; severity: "high" | "medium" | "low" | string }[];
  /** Segments d'edge pré-rendus par la page ("Paire · XAUUSD", "-800 € · 12 trades…"). */
  edge: { label: string; value: string; positive: boolean }[];
  strengths: string[];
  recommendations: string[];
  tradeReviews: { grade: string; pair: string; direction: string; date: string; pnl: number; comment: string }[];
  actionPlan: { title: string; target: string }[];
}

const LABELS = {
  fr: {
    kicker: "ANALYSE IA",
    title: "Rapport de discipline",
    generated: "Généré le",
    verdict: "Le verdict",
    kpis: "Vue d'ensemble",
    score: "Score discipline",
    trades: "Trades",
    netPnl: "P&L net",
    winrate: "Winrate",
    profitFactor: "Profit factor",
    violationCost: "Coût indiscipline",
    cost: "Le coût de l'indiscipline",
    costDesc: (n: number, clean: string, real: string) =>
      `${n} trade(s) hors stratégie. Discipline respectée, la période finirait à ${clean} au lieu de ${real}.`,
    costLucky: (amount: string) =>
      `Les trades hors stratégie ont rapporté ${amount} cette fois. De la chance, pas un edge.`,
    legendReal: "Réel",
    legendClean: "Discipline respectée",
    violations: "Violations détectées",
    patterns: "Patterns",
    evidence: "Preuve",
    edge: "Edge réel",
    strengths: "Points forts",
    recommendations: "Recommandations",
    reviews: "Trades passés au crible",
    thGrade: "Note",
    thTrade: "Trade",
    thPnl: "P&L",
    thComment: "Commentaire",
    plan: "Plan d'action",
    target: "Objectif",
    footer: "Analyse générée par l'IA TradeDiscipline. Ne constitue pas un conseil financier.",
  },
  en: {
    kicker: "AI ANALYSIS",
    title: "Discipline report",
    generated: "Generated on",
    verdict: "The verdict",
    kpis: "Overview",
    score: "Discipline score",
    trades: "Trades",
    netPnl: "Net P&L",
    winrate: "Win rate",
    profitFactor: "Profit factor",
    violationCost: "Indiscipline cost",
    cost: "The cost of indiscipline",
    costDesc: (n: number, clean: string, real: string) =>
      `${n} off-strategy trade(s). With discipline, the period would end at ${clean} instead of ${real}.`,
    costLucky: (amount: string) =>
      `Off-strategy trades made ${amount} this time. Luck, not an edge.`,
    legendReal: "Actual",
    legendClean: "Discipline followed",
    violations: "Violations detected",
    patterns: "Patterns",
    evidence: "Evidence",
    edge: "Real edge",
    strengths: "Strengths",
    recommendations: "Recommendations",
    reviews: "Trades under the microscope",
    thGrade: "Grade",
    thTrade: "Trade",
    thPnl: "P&L",
    thComment: "Comment",
    plan: "Action plan",
    target: "Target",
    footer: "Analysis generated by TradeDiscipline AI. Not financial advice.",
  },
  de: {
    kicker: "KI-ANALYSE",
    title: "Disziplin-Report",
    generated: "Erstellt am",
    verdict: "Das Urteil",
    kpis: "Überblick",
    score: "Disziplin-Score",
    trades: "Trades",
    netPnl: "Netto-P&L",
    winrate: "Winrate",
    profitFactor: "Profit Factor",
    violationCost: "Kosten Disziplinlosigkeit",
    cost: "Was Disziplinlosigkeit kostet",
    costDesc: (n: number, clean: string, real: string) =>
      `${n} Trade(s) außerhalb der Strategie. Mit Disziplin würde die Periode bei ${clean} statt ${real} enden.`,
    costLucky: (amount: string) =>
      `Trades außerhalb der Strategie brachten diesmal ${amount}. Glück, kein Edge.`,
    legendReal: "Real",
    legendClean: "Disziplin eingehalten",
    violations: "Erkannte Verstöße",
    patterns: "Muster",
    evidence: "Beleg",
    edge: "Echter Edge",
    strengths: "Stärken",
    recommendations: "Empfehlungen",
    reviews: "Trades unter der Lupe",
    thGrade: "Note",
    thTrade: "Trade",
    thPnl: "P&L",
    thComment: "Kommentar",
    plan: "Aktionsplan",
    target: "Ziel",
    footer: "Von der TradeDiscipline-KI erstellte Analyse. Keine Finanzberatung.",
  },
  es: {
    kicker: "ANÁLISIS IA",
    title: "Informe de disciplina",
    generated: "Generado el",
    verdict: "El veredicto",
    kpis: "Resumen",
    score: "Puntuación disciplina",
    trades: "Trades",
    netPnl: "P&L neto",
    winrate: "Winrate",
    profitFactor: "Profit factor",
    violationCost: "Coste indisciplina",
    cost: "El coste de la indisciplina",
    costDesc: (n: number, clean: string, real: string) =>
      `${n} trade(s) fuera de estrategia. Con disciplina, el periodo terminaría en ${clean} en lugar de ${real}.`,
    costLucky: (amount: string) =>
      `Los trades fuera de estrategia ganaron ${amount} esta vez. Suerte, no un edge.`,
    legendReal: "Real",
    legendClean: "Disciplina respetada",
    violations: "Violaciones detectadas",
    patterns: "Patrones",
    evidence: "Prueba",
    edge: "Edge real",
    strengths: "Puntos fuertes",
    recommendations: "Recomendaciones",
    reviews: "Trades bajo la lupa",
    thGrade: "Nota",
    thTrade: "Trade",
    thPnl: "P&L",
    thComment: "Comentario",
    plan: "Plan de acción",
    target: "Objetivo",
    footer: "Análisis generado por la IA de TradeDiscipline. No es asesoramiento financiero.",
  },
} as const;

function scoreColor(score: number): RGB {
  if (score >= 75) return C.green;
  if (score >= 50) return C.amber;
  return C.red;
}

const GRADE_COLORS: Record<string, RGB> = {
  A: C.green,
  B: C.teal,
  C: C.amber,
  D: C.red,
};

/** Courbe contrefactuelle : deux lignes (réel vs discipline) + grille + légende. */
function dualLineChart(
  p: Pdf,
  points: { real: number; clean: number }[],
  legends: { real: string; clean: string },
) {
  if (points.length < 2) return;
  const doc = p.doc;
  const chartH = 46;
  const labelW = 16;
  const chartX = p.M + labelW;
  const chartW = p.cw - labelW;
  const chartY = p.y;

  const values = points.flatMap((pt) => [pt.real, pt.clean]);
  const rawMin = Math.min(...values, 0);
  const rawMax = Math.max(...values, 0);
  const pad = Math.max((rawMax - rawMin) * 0.08, 1);
  const minVal = rawMin - pad;
  const maxVal = rawMax + pad;
  const range = maxVal - minVal || 1;

  const px = (i: number) => chartX + (i / (points.length - 1)) * chartW;
  const py = (v: number) => chartY + chartH - ((v - minVal) / range) * chartH;

  // Grille + labels Y
  doc.setFont(p.font, "normal");
  doc.setFontSize(6.4);
  for (let g = 0; g <= 3; g++) {
    const gy = chartY + (g / 3) * chartH;
    const gv = maxVal - (g / 3) * range;
    doc.setDrawColor(...C.lineSoft);
    doc.setLineWidth(0.25);
    doc.line(chartX, gy, chartX + chartW, gy);
    doc.setTextColor(...C.faint);
    doc.text(money(gv, 0), chartX - 2.5, gy + 1.7, { align: "right" });
  }

  const drawLine = (get: (pt: { real: number; clean: number }) => number, color: RGB, width: number) => {
    doc.setLineCap("round");
    doc.setLineJoin("round");
    doc.setDrawColor(...color);
    doc.setLineWidth(width);
    for (let i = 1; i < points.length; i++) {
      doc.line(px(i - 1), py(get(points[i - 1])), px(i), py(get(points[i])));
    }
    doc.setLineCap("butt");
    doc.setLineJoin("miter");
    // Point final
    const last = points[points.length - 1];
    doc.setFillColor(...color);
    doc.circle(px(points.length - 1), py(get(last)), 1.2, "F");
  };

  drawLine((pt) => pt.real, C.muted, 0.8);
  drawLine((pt) => pt.clean, C.green, 1.1);

  // Légende sous le graphe
  let lx = chartX;
  const legendRow: { label: string; color: RGB; value: string }[] = [
    { label: legends.clean, color: C.green, value: signedMoney(points[points.length - 1].clean, 0) },
    { label: legends.real, color: C.muted, value: signedMoney(points[points.length - 1].real, 0) },
  ];
  const ly = chartY + chartH + 6;
  doc.setFontSize(7.2);
  for (const item of legendRow) {
    doc.setFillColor(...item.color);
    doc.roundedRect(lx, ly - 2.4, 5, 1.4, 0.7, 0.7, "F");
    doc.setFont(p.font, "normal");
    doc.setTextColor(...C.inkSoft);
    const label = `${item.label} · `;
    doc.text(label, lx + 6.5, ly);
    doc.setFont(p.font, "bold");
    doc.setTextColor(...item.color);
    doc.text(item.value, lx + 6.5 + doc.getTextWidth(label), ly);
    lx += 6.5 + doc.getTextWidth(label) + doc.getTextWidth(item.value) + 10;
  }

  p.y = ly + 9;
}

export async function buildAnalysisPdf(data: AnalysisPdfData): Promise<jsPDF> {
  const L = LABELS[data.lang] ?? LABELS.fr;
  const doc = new jsPDF();
  const font = await ensureBrandFont(doc);
  const p = new Pdf(doc, { font });

  const dateStr = new Date().toLocaleDateString(
    { fr: "fr-FR", en: "en-GB", de: "de-DE", es: "es-ES" }[data.lang] ?? "fr-FR",
    { day: "numeric", month: "long", year: "numeric" },
  );

  p.header({
    kicker: L.kicker,
    title: L.title,
    subtitle: `${data.periodLabel} · ${L.generated} ${dateStr}`,
  });

  // ── Verdict ──
  if (data.headline) {
    p.section(L.verdict);
    doc.setFont(font, "bold");
    doc.setFontSize(11.5);
    doc.setTextColor(...C.ink);
    const headLines = doc.splitTextToSize(data.headline, p.cw) as string[];
    doc.text(headLines, p.M, p.y);
    p.y += headLines.length * 5.6 + 2;
    if (data.summary) p.paragraph(data.summary);
    p.y += 2;
  }

  // ── KPI ──
  p.section(L.kpis);
  const s = data.stats;
  const cards: { label: string; value: string; color?: RGB }[] = [
    { label: L.score, value: `${data.score}/100`, color: scoreColor(data.score) },
    { label: L.trades, value: groupNum(data.totalTrades) },
  ];
  if (s) {
    cards.push(
      { label: L.netPnl, value: signedMoney(s.netPnl), color: s.netPnl >= 0 ? C.green : C.red },
      { label: L.winrate, value: `${groupNum(s.winRate)} %` },
      { label: L.profitFactor, value: s.profitFactor == null ? "∞" : groupNum(s.profitFactor, 2) },
      { label: L.violationCost, value: signedMoney(s.violationCost), color: s.violationCost < 0 ? C.red : C.green },
    );
  }
  p.statGrid(cards, { cols: 3 });

  // ── Coût de l'indiscipline + courbe contrefactuelle ──
  const cf = data.counterfactual;
  if (cf && s && s.violationTradeCount > 0) {
    p.ensure(80, L.title);
    p.section(L.cost, { spaceBefore: 2 });
    p.paragraph(
      s.violationCost < 0
        ? L.costDesc(s.violationTradeCount, signedMoney(cf.cleanFinal), signedMoney(cf.realFinal))
        : L.costLucky(signedMoney(s.violationCost)),
      { accent: true },
    );
    dualLineChart(p, cf.points, { real: L.legendReal, clean: L.legendClean });
  }

  // ── Violations ──
  if (data.violations.length > 0) {
    p.ensure(30, L.title);
    p.section(L.violations, { spaceBefore: 2 });
    for (const v of data.violations) {
      p.ensure(16, L.title);
      const costStr = typeof v.cost === "number" ? `  (${signedMoney(v.cost)})` : "";
      p.bullet(`${v.title}${costStr} : ${v.explanation}`, { color: C.red });
    }
  }

  // ── Patterns ──
  if (data.patterns.length > 0) {
    p.ensure(30, L.title);
    p.section(L.patterns, { spaceBefore: 2 });
    for (const pat of data.patterns) {
      p.ensure(20, L.title);
      const sevColor = pat.severity === "high" ? C.red : pat.severity === "medium" ? C.amber : C.teal;
      p.bullet(`${pat.title} : ${pat.description}`, { color: sevColor });
      if (pat.evidence) {
        doc.setFont(font, "normal");
        doc.setFontSize(8);
        doc.setTextColor(...C.muted);
        const evLines = doc.splitTextToSize(`${L.evidence} : ${pat.evidence}`, p.cw - 10) as string[];
        doc.text(evLines, p.M + 6, p.y - 0.5);
        p.y += evLines.length * 4 + 2;
      }
    }
  }

  // ── Edge ──
  if (data.edge.length > 0) {
    p.ensure(26, L.title);
    p.section(L.edge, { spaceBefore: 2 });
    for (const e of data.edge) {
      p.bullet(`${e.label} : ${e.value}`, { color: e.positive ? C.green : C.red });
    }
  }

  // ── Points forts / Recommandations ──
  if (data.strengths.length > 0) {
    p.ensure(26, L.title);
    p.section(L.strengths, { spaceBefore: 2 });
    for (const st of data.strengths) {
      p.ensure(12, L.title);
      p.bullet(st, { color: C.green });
    }
  }
  if (data.recommendations.length > 0) {
    p.ensure(26, L.title);
    p.section(L.recommendations, { spaceBefore: 2 });
    data.recommendations.forEach((r, i) => {
      p.ensure(12, L.title);
      p.bullet(r, { index: i + 1 });
    });
  }

  // ── Revue des trades ──
  if (data.tradeReviews.length > 0) {
    p.ensure(40, L.title);
    p.section(L.reviews, { spaceBefore: 2 });
    p.table(
      [
        { header: L.thGrade, w: 0.08 },
        { header: L.thTrade, w: 0.24 },
        { header: L.thPnl, w: 0.13, align: "right" },
        { header: L.thComment, w: 0.55 },
      ],
      data.tradeReviews.map((r) => {
        const gradeColor = GRADE_COLORS[r.grade] ?? C.amber;
        // Le commentaire est tronqué à la largeur de colonne (1 ligne).
        const maxW = 0.55 * p.cw - 4;
        let comment = r.comment;
        doc.setFontSize(8.3);
        while (doc.getTextWidth(comment) > maxW && comment.length > 8) {
          comment = comment.slice(0, -6).trimEnd() + "…";
        }
        return [
          { text: r.grade, color: gradeColor, bold: true },
          { text: `${r.pair} ${r.direction.toUpperCase()} · ${r.date}` },
          { text: signedMoney(r.pnl), color: r.pnl >= 0 ? C.green : C.red, bold: true },
          { text: comment },
        ];
      }),
      { contTitle: L.title },
    );
  }

  // ── Plan d'action ──
  if (data.actionPlan.length > 0) {
    p.ensure(30, L.title);
    p.section(L.plan, { spaceBefore: 2 });
    data.actionPlan.forEach((a, i) => {
      p.ensure(14, L.title);
      p.bullet(`${a.title} (${L.target} : ${a.target})`, { index: i + 1, color: C.cyan });
    });
  }

  p.footer(L.footer);
  return doc;
}

export async function exportAnalysisPdf(data: AnalysisPdfData) {
  const doc = await buildAnalysisPdf(data);
  doc.save(`tradediscipline_analyse_${new Date().toISOString().split("T")[0]}.pdf`);
}
